<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-9NL11TP" failures="1" tests="5" name="allTest" time="11.687" errors="0" timestamp="2021-10-11T08:25:35 AEDT">
  <testcase classname="pages.Contact2" name="validateTitle" time="0.066">
    <failure type="java.lang.AssertionError" message="expected [contact] but found [AspiringTester]">
      <![CDATA[java.lang.AssertionError: expected [contact] but found [AspiringTester]
at pages.Contact2.validateTitle(Contact2.java:56)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:831)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- validateTitle -->
  <testcase classname="pages.Contact2" name="presenceOfNavbar" time="0.162"/>
  <testcase classname="pages.Contact2" name="formTesting" time="1.122"/>
  <testcase classname="pages.Contact2" name="formTesting" time="0.815"/>
  <testcase classname="pages.Contact2" name="formTesting" time="0.854"/>
</testsuite> <!-- allTest -->
