<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-9NL11TP" failures="1" tests="5" name="pages.Contact2" time="3.019" errors="0" timestamp="2021-10-11T08:25:36 AEDT" skipped="0">
  <testcase classname="pages.Contact2" name="formTesting" time="0.854"/>
  <system-out/>
  <testcase classname="pages.Contact2" name="formTesting" time="0.815"/>
  <system-out/>
  <testcase classname="pages.Contact2" name="validateTitle" time="0.066">
    <failure message="expected [contact] but found [AspiringTester]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [contact] but found [AspiringTester]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at pages.Contact2.validateTitle(Contact2.java:56)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:831)
]]>
    </failure>
  </testcase> <!-- validateTitle -->
  <system-out/>
  <testcase classname="pages.Contact2" name="presenceOfNavbar" time="0.162"/>
  <system-out/>
  <testcase classname="pages.Contact2" name="formTesting" time="1.122"/>
  <system-out/>
</testsuite> <!-- pages.Contact2 -->
